name: download_on_issue
on:
  issues:
    types:
      - opened
      - reopened
jobs:
  parse_issue:
    runs-on: ubuntu-latest
    outputs:
      device: ${{steps.parser.outputs.DEVICE}}
      tag: ${{steps.parser.outputs.TAG}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - id: parser
        run: ALT_MAIN=PARSE_ISSUE go run . '${{ github.event.issue.body }}'
  echo_output:
    runs-on: ubuntu-latest
    needs: [parse_issue]
    steps:
      - name: echo_input
        run: |
          echo "${{needs.parse_issue.outputs.device}}"
          echo "${{needs.parse_issue.outputs.tag}}"
  call_reuse:
    needs: [parse_issue]
    uses: ./.github/workflows/download.reuse.yaml
    with:
      device: ${{ needs.parse_issue.outputs.device }}
      tag: ${{ needs.parse_issue.outputs.tag }}
    secrets: inherit
